name: Deploy to EC2
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - run: chmod +x gradlew
      - run: ./gradlew clean bootJar -x test
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ec2-user/awsTest/"
      - name: Restart app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            mkdir -p /home/ec2-user/awsTest
            cd /home/ec2-user/awsTest
            JAR=$(ls *.jar | grep -v 'plain' | sort | tail -n 1)
            pkill -f "java.*$JAR" || pkill -f "java.*build/libs" || true
            nohup java -jar "$JAR" > app.log 2>&1 &
            sleep 3
            pgrep -f "$JAR"
