name: Deploy to EC2

on:
  push:
    branches:
      - main   # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/awsTest || git clone https://github.com/hansolChoi29/awsTest.git
            cd awsTest
            git pull origin main
            ./gradlew build
            nohup java -jar build/libs/*.jar > app.log 2>&1 &
